import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import "typeface-poppins"
import App from "../components/App"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <meta name="description" content="An app to create and access encrypted notes on the cloud." />
        <meta name="keywords" content="cyfer, cipher, notes, nextjs" />
        <meta name="author" content="Fawaz Haroun" />
        <meta property="og:title" content="Cyfer" />
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="Cyfer" />
        <meta property="og:url" content="https://cyfer.vercel.app/" />
        <meta property="og:image" content="/favicon.ico" />
        <meta property="og:image:type" content="image/ico" />
        <meta property="og:image:width" content="1200" />
        <meta property="og:image:height" content="1200" />
        <meta property="og:locale" content="en_US" />

        <meta property="twitter:site" content="Cyfer" />
        <meta property="twitter:creator" content="exalted100" />
        <meta property="twitter:card" content="summary_large_image" />
        <meta property="twitter:title" content="Cyfer" />
        <meta property="twitter:description" content="An app to create and access encrypted notes on the cloud." />
        <meta property="twitter:image:src" content="/favicon.ico" />
        <meta property="twitter:image:width" content="1200" />
        <meta property="twitter:image:height" content="1200" />

        <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
        <title>Cyfer</title>
      </Head>

      <main className={styles.main}>
        <App />
      </main>
    </div>
  )
}

// Landing Page
// Signup Page
// Login page
// Activate account page
// Profile page
// display note page
// decrypt note modal
// type new note page
// edit note page
// All notes page
// delete account page
//404.ts page

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <App />
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/master/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }